#!/opt/homebrew/bin/zsh 
echo "hello!"
#dir_name="~/workspace/my_awesome_linux/sc/shell_scripts/"
dir_name=~/workspace/my_awesome_linux/sc/shell_scripts/
cp ~/.emacs ~/workspace/my_awesome_linux/sc/shell_scripts/
cp -rf ~/.emacs.d ~/workspace/my_awesome_linux/sc/shell_scripts/
cp ~/.vimrc ~/workspace/my_awesome_linux/sc/shell_scripts/
echo $dir_name
cp ~/.gitconfig $dir_name
cp ~/.my_zshrc $dir_name
